import { promises as fs } from 'node:fs';
import process from 'node:process';

function argsOf(argv){const o={};for(let i=2;i<argv.length;i+=2){if(!argv[i]?.startsWith('--')) throw new Error('bad args');o[argv[i].slice(2)]=argv[i+1];}return o;}
const args=argsOf(process.argv);
const base=args.url;
const report=args.report;
const endpoint=process.env.CDP_ENDPOINT||'http://127.0.0.1:9333';
if(!base||!report) throw new Error('Usage: node v24_interaction_matrix.mjs --url <preview> --report <json>');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitChrome(){for(let i=0;i<80;i++){try{const r=await fetch(endpoint+'/json/version');if(r.ok)return;}catch{}await sleep(125);}throw new Error('CDP unavailable');}
await waitChrome();
const tr=await fetch(endpoint+'/json/new?'+encodeURIComponent('about:blank'),{method:'PUT'});
if(!tr.ok) throw new Error('target create HTTP '+tr.status);
const target=await tr.json();
const ws=new WebSocket(target.webSocketDebuggerUrl);
await new Promise((res,rej)=>{ws.addEventListener('open',res,{once:true});ws.addEventListener('error',rej,{once:true});});
let id=0;const pending=new Map();const waiters=new Map();const runtimeErrors=[];
ws.addEventListener('message',ev=>{const m=JSON.parse(ev.data);if(m.id){const p=pending.get(m.id);if(!p)return;pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result||{});return;}if(m.method==='Runtime.exceptionThrown'||(m.method==='Log.entryAdded'&&m.params?.entry?.level==='error'))runtimeErrors.push(m);const q=waiters.get(m.method);if(q?.length)q.shift()(m.params||{});});
function send(method,params={}){return new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));setTimeout(()=>{if(pending.has(n)){pending.delete(n);reject(new Error('timeout '+method));}},15000);});}
function once(method,ms=15000){return new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('wait '+method)),ms);const f=x=>{clearTimeout(t);resolve(x)};const q=waiters.get(method)||[];q.push(f);waiters.set(method,q);});}
async function evalv(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text||'evaluation failed');return r.result?.value;}
async function viewport(width,height){await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false,screenWidth:width,screenHeight:height,positionX:0,positionY:0,dontSetVisibleSize:false});}
async function nav(url){const loaded=once('Page.loadEventFired');const r=await send('Page.navigate',{url});if(r.errorText)throw new Error(r.errorText);await loaded;await evalv(`(async()=>{await document.fonts?.ready;await Promise.all([...document.images].map(i=>i.complete?1:new Promise(r=>{i.onload=i.onerror=r})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return true})()`);}
const R={contract:'BLACKGOLD_V24_RUNTIME_INTERACTION_MATRIX',generated_at:new Date().toISOString(),tests:[],warnings:['PT/EN/ES runtime switching remains blocked until separate approved translated authorities exist.']};
async function test(name,fn){const t=Date.now();try{const data=await fn();R.tests.push({name,result:'PASS',ms:Date.now()-t,data});}catch(e){R.tests.push({name,result:'FAIL',ms:Date.now()-t,error:String(e?.stack||e)});}}
await send('Page.enable');await send('Runtime.enable');await send('Log.enable');

async function visibleHits(prefix){return await evalv(`(()=>[...document.querySelectorAll('a.hit.${prefix}')].filter(a=>{const r=a.getBoundingClientRect(),s=getComputedStyle(a);return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0}).map(a=>{const r=a.getBoundingClientRect();return {c:[...a.classList].filter(x=>x!=='hit'&&x!=='d'&&x!=='m')[0],href:a.getAttribute('href'),label:a.getAttribute('aria-label'),w:r.width,h:r.height,x:r.x,y:r.y}}))()`);}
async function assertInternal(className,expectedPath,width,height){await viewport(width,height);await nav(base+'/');const ok=await evalv(`(()=>{const a=document.querySelector('.${className}');if(!a)return false;a.click();return true})()`);if(!ok)throw new Error('missing '+className);await sleep(250);const x=await evalv(`({path:location.pathname,origin:location.origin})`);const clean=expectedPath.endsWith('.html')?expectedPath.slice(0,-5):expectedPath;if(!(x.path.endsWith(expectedPath)||x.path.endsWith(clean)))throw new Error(className+' -> '+JSON.stringify(x));return {...x,expected:expectedPath,acceptedCleanPath:clean};}

await test('desktop_geometry_and_visibility',async()=>{await viewport(1448,1086);await nav(base+'/');const x=await evalv(`({innerWidth,innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,d:[...document.querySelectorAll('a.hit.d')].filter(a=>getComputedStyle(a).display!=='none').length,m:[...document.querySelectorAll('a.hit.m')].filter(a=>getComputedStyle(a).display!=='none').length})`);if(x.innerWidth!==1448||x.innerHeight!==1086||x.scrollWidth!==1448||x.d<15||x.m!==0)throw new Error(JSON.stringify(x));return x;});
await test('mobile_geometry_and_visibility',async()=>{await viewport(390,1152);await nav(base+'/');const x=await evalv(`({innerWidth,innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,d:[...document.querySelectorAll('a.hit.d')].filter(a=>getComputedStyle(a).display!=='none').length,m:[...document.querySelectorAll('a.hit.m')].filter(a=>getComputedStyle(a).display!=='none').length})`);if(x.innerWidth!==390||x.innerHeight!==1152||x.scrollWidth!==390||x.d!==0||x.m<14)throw new Error(JSON.stringify(x));return x;});
await test('mobile_touch_targets_runtime',async()=>{await viewport(390,1152);await nav(base+'/');const hits=await visibleHits('m');const bad=hits.filter(x=>x.w<44||x.h<44);if(bad.length)throw new Error('touch targets '+JSON.stringify(bad));return {checked:hits.length,minW:Math.min(...hits.map(x=>x.w)),minH:Math.min(...hits.map(x=>x.h))};});
await test('desktop_internal_navigation',async()=>{const cases=[['d-destaque','/destaque.html'],['d-vitrine','/vitrine.html'],['d-eco','/ecossistema.html'],['d-explore','/destaque.html'],['d-openeco','/ecossistema.html'],['d-allselection','/destaque.html'],['d-detail1','/vitrine.html'],['d-detail2','/vitrine.html'],['d-detail3','/vitrine.html'],['d-allvitrine','/vitrine.html']];const out=[];for(const c of cases)out.push({c:c[0],nav:await assertInternal(c[0],c[1],1448,1086)});return out;});
await test('mobile_internal_navigation',async()=>{const cases=[['m-menu','/ecossistema.html'],['m-search','/vitrine.html'],['m-bag','/vitrine.html'],['m-explore','/destaque.html'],['m-openeco','/ecossistema.html'],['m-allselection','/destaque.html'],['m-detail','/vitrine.html'],['m-allvitrine','/vitrine.html']];const out=[];for(const c of cases)out.push({c:c[0],nav:await assertInternal(c[0],c[1],390,1152)});return out;});
await test('internal_targets_http_200',async()=>{await viewport(1448,1086);await nav(base+'/');const refs=await evalv(`([...new Set([...document.querySelectorAll('a.hit[href]')].map(a=>a.href).filter(h=>h.startsWith(location.origin)))])`);const bad=[];for(const u of refs){const r=await fetch(u,{redirect:'follow'});if(!r.ok)bad.push({u,status:r.status});}if(bad.length)throw new Error(JSON.stringify(bad));return {checked:refs.length,broken:0};});
await test('official_external_runtime_contract',async()=>{await viewport(1448,1086);await nav(base+'/');const x=await evalv(`(()=>{const want={hub:'https://blackgold-beauty-finds-br.pages.dev/',instagram:'https://www.instagram.com/cosanostra.blackgold/',youtube:'https://www.youtube.com/@cosanostra.blackgold',telegram:'https://t.me/BlackGoldSociety',github:'https://github.com/ProjetosCosaNostra',contact:'mailto:projetoscosanostra@gmail.com'};const get=c=>{const a=document.querySelector('.d-'+c);return a?{href:a.getAttribute('href'),target:a.target,rel:a.rel}:null};return Object.fromEntries(Object.keys(want).map(k=>[k,{want:want[k],got:get(k)}]));})()`);for(const [k,v] of Object.entries(x)){if(!v.got||v.got.href!==v.want)throw new Error(k+' mismatch '+JSON.stringify(v));if(v.want.startsWith('http')&&(v.got.target!=='_blank'||!v.got.rel.split(/\s+/).includes('noopener')))throw new Error(k+' external safety '+JSON.stringify(v));}return x;});
async function keyboardCycle(width,height,prefix){await viewport(width,height);await nav(base+'/');await evalv(`document.activeElement?.blur();scrollTo(0,0);true`);const expected=await visibleHits(prefix);const seen=[];for(let i=0;i<expected.length;i++){await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,nativeVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,nativeVirtualKeyCode:9});await sleep(30);const a=await evalv(`(()=>{const e=document.activeElement,r=e?.getBoundingClientRect?.(),s=e?getComputedStyle(e):null;return {tag:e?.tagName||'',c:e?.className||'',href:e?.getAttribute?.('href')||'',w:r?.width||0,h:r?.height||0,outline:s?.outlineStyle||'',outlineWidth:s?.outlineWidth||''}})()`);seen.push(a);}const bad=seen.filter(x=>x.tag!=='A'||!x.c.includes('hit'));if(bad.length)throw new Error('keyboard escaped hotspots '+JSON.stringify(bad));const classes=seen.map(x=>(x.c.match(/\b[dm]-[\w-]+/)||[])[0]).filter(Boolean);if(new Set(classes).size!==expected.length)throw new Error('keyboard coverage '+JSON.stringify({expected:expected.length,unique:new Set(classes).size,classes}));const first=seen[0];if(first.outline==='none'||parseFloat(first.outlineWidth||'0')<3)throw new Error('focus indicator '+JSON.stringify(first));return {expected:expected.length,unique:new Set(classes).size,classes,firstFocus:first};}
await test('desktop_keyboard_focus_cycle',async()=>keyboardCycle(1448,1086,'d'));
await test('mobile_keyboard_focus_cycle',async()=>{const r=await keyboardCycle(390,1152,'m');return r;});
await test('semantic_content_runtime',async()=>{await viewport(390,1152);await nav(base+'/');const x=await evalv(`(()=>({h1:[...document.querySelectorAll('h1')].map(e=>e.textContent.trim()),h2:[...document.querySelectorAll('h2')].map(e=>e.textContent.trim()),pictureHidden:document.querySelector('picture')?.getAttribute('aria-hidden'),imgAlt:document.querySelector('picture img')?.getAttribute('alt')}))()`);if(!x.h1.includes('Curadoria feminina com presença premium.')||!x.h2.includes('Seleção do Dia')||!x.h2.includes('Vitrine Premium')||!x.h2.includes('Ecossistema BlackGold')||x.pictureHidden!=='true'||x.imgAlt!=='')throw new Error(JSON.stringify(x));return x;});
await test('no_mojibake_runtime',async()=>{await viewport(1448,1086);await nav(base+'/');const x=await evalv(`({text:document.documentElement.innerHTML.includes('Ã')||document.documentElement.innerHTML.includes('�'),labels:[...document.querySelectorAll('a.hit')].map(a=>a.getAttribute('aria-label'))})`);if(x.text||x.labels.some(v=>/[Ã�]/.test(v||'')))throw new Error(JSON.stringify(x));return {labels:x.labels.length};});
R.runtime_errors=runtimeErrors.map(x=>({method:x.method,params:x.params})).slice(-50);
R.summary={pass:R.tests.filter(x=>x.result==='PASS').length,fail:R.tests.filter(x=>x.result==='FAIL').length,total:R.tests.length,runtime_errors:R.runtime_errors.length};
R.summary.result=(R.summary.fail===0&&R.summary.runtime_errors===0)?'GREEN':'BLOCKED';
await fs.mkdir(new URL('.', 'file:///'+report.replace(/\\/g,'/')).pathname,{recursive:true}).catch(()=>{});
await fs.mkdir(report.replace(/[\\/][^\\/]+$/,''),{recursive:true}).catch(()=>{});
await fs.writeFile(report,JSON.stringify(R,null,2),'utf8');
console.log(JSON.stringify(R.summary));
for(const t of R.tests) console.log(`${t.result} ${t.name}${t.error?' :: '+t.error:''}`);
try{await fetch(endpoint+'/json/close/'+target.id);}catch{}
try{ws.close();}catch{}
process.exit(R.summary.result==='GREEN'?0:2);
