const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='blackgold-admin-token-v2';const state={token:sessionStorage.getItem(KEY)||'',products:[],editing:null};
async function api(path,opt={}){const h=new Headers(opt.headers||{});if(state.token)h.set('authorization','Bearer '+state.token);if(opt.body&&!(opt.body instanceof FormData))h.set('content-type','application/json');const r=await fetch(path,{...opt,headers:h,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.message||d.code||('HTTP '+r.status)),{status:r.status});return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){state.products.length?$('#empty').style.display='none':$('#empty').style.display='grid';$('#list').innerHTML=state.products.map(p=>'<div class="row"><div><b>'+esc(p.title)+'</b><br><small>'+esc(p.status)+' · '+esc(p.category||'sem categoria')+'</small></div><div class="actions"><button data-edit="'+p.id+'">Editar</button><button data-toggle="'+p.id+'">'+(p.status==='published'?'Despublicar':'Publicar')+'</button><button data-del="'+p.id+'">Excluir</button></div></div>').join('');$$('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));$$('[data-toggle]').forEach(b=>b.onclick=()=>toggle(b.dataset.toggle));$$('[data-del]').forEach(b=>b.onclick=()=>del(b.dataset.del))}
async function load(){state.products=(await api('/api/admin/products')).products||[];render()}
async function unlock(t){state.token=t;try{await load();sessionStorage.setItem(KEY,t);document.body.classList.add('unlocked');$('#lockStatus').textContent='';return true}catch(e){state.token='';sessionStorage.removeItem(KEY);$('#lockStatus').textContent=e.status===401?'Chave incorreta.':e.message;return false}}
$('#unlock').onsubmit=e=>{e.preventDefault();unlock($('#token').value.trim())};$('#logout').onclick=()=>{state.token='';sessionStorage.removeItem(KEY);document.body.classList.remove('unlocked')};
function open(p=null){state.editing=p;const f=$('#form');f.reset();f.elements.id.value=p?.id||'';f.elements.title.value=p?.title||'';f.elements.brand.value=p?.brand||'';f.elements.category.value=p?.category||'';f.elements.currency.value=p?.currency||'BRL';f.elements.price.value=p?.price??'';f.elements.order.value=p?.order??0;f.elements.description.value=p?.description||'';f.elements.destinationUrl.value=p?.destinationUrl||'';f.elements.imageKey.value=p?.imageKey||'';f.elements.imageUrl.value=p?.imageUrl||'';f.elements.status.value=p?.status||'draft';f.elements.featured.checked=!!p?.featured;$('#modal').classList.add('open')}
function edit(id){open(state.products.find(p=>p.id===id))}$('#new').onclick=()=>open();$('#cancel').onclick=()=>$('#modal').classList.remove('open');
async function toggle(id){const p=state.products.find(x=>x.id===id);await api('/api/admin/products',{method:'PATCH',body:JSON.stringify({id,status:p.status==='published'?'draft':'published'})});await load()}
async function del(id){if(!confirm('Excluir este produto?'))return;await api('/api/admin/products?id='+encodeURIComponent(id),{method:'DELETE'});await load()}
$('#imageFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const fd=new FormData();fd.append('file',file);const d=await api('/api/admin/upload',{method:'POST',body:fd});$('#form').elements.imageKey.value=d.key;$('#form').elements.imageUrl.value=''};
$('#form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const payload={id:state.editing?.id||undefined,title:f.elements.title.value,brand:f.elements.brand.value,category:f.elements.category.value,currency:f.elements.currency.value,price:f.elements.price.value,order:Number(f.elements.order.value||0),description:f.elements.description.value,destinationUrl:f.elements.destinationUrl.value,imageKey:f.elements.imageKey.value,imageUrl:f.elements.imageUrl.value,status:f.elements.status.value,featured:f.elements.featured.checked};const method=state.editing?'PATCH':'POST';if(!state.editing)delete payload.id;await api('/api/admin/products',{method,body:JSON.stringify(payload)});$('#modal').classList.remove('open');await load()};
if(state.token)unlock(state.token);