(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={products:[],lang:"pt",filter:"",query:""};
const text={pt:{title:"Vitrine completa",search:"Buscar produto, marca ou categoria",empty:"Nenhum produto publicado.",details:"Ver detalhes →",affiliate:"Alguns links podem ser afiliados: a BlackGold pode receber comissão sem custo adicional para você."},en:{title:"Full showcase",search:"Search product, brand or category",empty:"No products published.",details:"View details →",affiliate:"Some links may be affiliate links: BlackGold may earn a commission at no additional cost to you."},es:{title:"Vitrina completa",search:"Buscar producto, marca o categoría",empty:"No hay productos publicados.",details:"Ver detalles →",affiliate:"Algunos enlaces pueden ser de afiliados: BlackGold puede recibir una comisión sin costo adicional para ti."}};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=p=>p.price==null?"":new Intl.NumberFormat(state.lang==="en"?"en-US":state.lang==="es"?"es-ES":"pt-BR",{style:"currency",currency:p.currency||"BRL"}).format(Number(p.price));
function outHref(p,placement="unknown"){const safePlacement=["selection","showcase","catalog"].includes(placement)?placement:"unknown";return "/api/out?id="+encodeURIComponent(p.id)+"&placement="+encodeURIComponent(safePlacement)}
function featured(p){return '<article class="product"><div class="media">'+(p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.title)+'">':"")+'</div><div class="copy"><h3>'+esc(p.title)+'</h3><span class="meta">'+esc(p.brand||p.category||"BlackGold")+'</span><p class="desc">'+esc(p.description||"")+'</p>'+(money(p)?'<strong class="price">'+esc(money(p))+'</strong>':"")+'<a class="detail" href="'+esc(outHref(p,"selection"))+'" target="_blank" rel="noopener noreferrer sponsored" aria-label="'+esc(text[state.lang].details+" "+p.title)+'">'+text[state.lang].details+'</a></div></article>'}
function small(p){return '<a class="product product-link" href="'+esc(outHref(p,"showcase"))+'" target="_blank" rel="noopener noreferrer sponsored" aria-label="'+esc(p.title)+'"><div class="media">'+(p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.title)+'">':"")+'</div><h3>'+esc(p.title)+'</h3>'+(money(p)?'<strong class="price">'+esc(money(p))+'</strong>':"")+'</a>'}
function catalogCard(p){return '<a class="catalog-card" href="'+esc(outHref(p,"catalog"))+'" target="_blank" rel="noopener noreferrer sponsored" aria-label="'+esc(p.title)+'">'+(p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.title)+'">':'')+'<div><h3>'+esc(p.title)+'</h3><small>'+esc(p.brand||p.category||"BlackGold")+'</small>'+(money(p)?'<strong>'+esc(money(p))+'</strong>':'')+'</div></a>'}
function filtered(){const q=state.query.toLowerCase();return state.products.filter(p=>(!state.filter||p.category===state.filter)&&(!q||[p.title,p.brand,p.category,p.description].join(" ").toLowerCase().includes(q)))}
function renderCatalog(){const rows=filtered();$("#catalogGrid").innerHTML=rows.map(catalogCard).join("");$("#catalogEmpty").classList.toggle("show",rows.length===0)}
function render(){const n=state.products.length;document.body.classList.toggle("has-products",n>0);document.body.dataset.catalogCount=String(n);const count=$("#catalogCountLive");if(count){const b=count.querySelector("b");const s=count.querySelector("small");if(b)b.textContent=String(n);if(s)s.textContent=n===1?"produto ativo":"produtos ativos"}$("#selection").innerHTML=state.products.filter(x=>x.featured).slice(0,3).map(featured).join("");$("#showcase").innerHTML=state.products.filter(x=>!x.featured).slice(0,8).map(small).join("");renderCatalog()}
async function load(){try{const r=await fetch("/api/products?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw 0;const d=await r.json();state.products=Array.isArray(d.products)?d.products:[]}catch{state.products=[]}render()}
function applyLang(lang){state.lang=lang||"pt";document.documentElement.lang=state.lang==="pt"?"pt-BR":state.lang==="en"?"en-US":"es";$("#catalogTitle").textContent=text[state.lang].title;$("#catalogSearch").placeholder=text[state.lang].search;$("#catalogEmpty").textContent=text[state.lang].empty;const note=$("#affiliateNote");if(note&&note.firstChild)note.firstChild.nodeValue=text[state.lang].affiliate+" ";render()}
function openCatalog(){const d=$("#catalogDialog");if(!d.open)d.showModal();setTimeout(()=>$("#catalogSearch").focus(),30)}
function geometry(){const img=$(".authority-picture img");if(!img)return;document.documentElement.dataset.renderWidth=String(Math.round(img.getBoundingClientRect().width));document.documentElement.dataset.viewportWidth=String(window.innerWidth);document.documentElement.dataset.horizontalOverflow=String(document.documentElement.scrollWidth>window.innerWidth)}
$$("[data-lang]").forEach(b=>b.onclick=()=>applyLang(b.dataset.lang));$$("[data-open-catalog]").forEach(b=>b.onclick=openCatalog);
$("#catalogSearch").oninput=e=>{state.query=e.target.value||"";renderCatalog()};$$("[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter||"";$$("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));renderCatalog()});$("[data-filter='']").classList.add("active");
window.addEventListener("resize",geometry);requestAnimationFrame(geometry);setTimeout(geometry,200);load();
})();