(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={products:[],lang:"pt",filter:"",query:""};
const text={pt:{title:"Vitrine completa",search:"Buscar produto, marca ou categoria",empty:"Nenhum produto publicado.",details:"Ver detalhes →"},en:{title:"Full showcase",search:"Search product, brand or category",empty:"No products published.",details:"View details →"},es:{title:"Vitrina completa",search:"Buscar producto, marca o categoría",empty:"No hay productos publicados.",details:"Ver detalles →"}};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=p=>p.price==null?"":new Intl.NumberFormat(state.lang==="en"?"en-US":state.lang==="es"?"es-ES":"pt-BR",{style:"currency",currency:p.currency||"BRL"}).format(Number(p.price));
function openProduct(id,placement="unknown"){const p=state.products.find(x=>String(x.id)===String(id));if(!p)return;const safePlacement=["selection","showcase","catalog"].includes(placement)?placement:"unknown";window.open("/api/out?id="+encodeURIComponent(p.id)+"&placement="+encodeURIComponent(safePlacement),"_blank","noopener,noreferrer")}
function featured(p){return '<article class="product"><div class="media">'+(p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.title)+'">':"")+'</div><div class="copy"><h3>'+esc(p.title)+'</h3><span class="meta">'+esc(p.brand||p.category||"BlackGold")+'</span><p class="desc">'+esc(p.description||"")+'</p>'+(money(p)?'<strong class="price">'+esc(money(p))+'</strong>':"")+'<button class="detail" data-product="'+esc(p.id)+'" data-placement="selection">'+text[state.lang].details+'</button></div></article>'}
function small(p){return '<article class="product" data-product="'+esc(p.id)+'" data-placement="showcase"><div class="media">'+(p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.title)+'">':"")+'</div><h3>'+esc(p.title)+'</h3>'+(money(p)?'<strong class="price">'+esc(money(p))+'</strong>':"")+'</article>'}
function catalogCard(p){return '<article class="catalog-card" data-product="'+esc(p.id)+'" data-placement="catalog">'+(p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.title)+'">':'')+'<div><h3>'+esc(p.title)+'</h3><small>'+esc(p.brand||p.category||"BlackGold")+'</small>'+(money(p)?'<strong>'+esc(money(p))+'</strong>':'')+'</div></article>'}
function filtered(){const q=state.query.toLowerCase();return state.products.filter(p=>(!state.filter||p.category===state.filter)&&(!q||[p.title,p.brand,p.category,p.description].join(" ").toLowerCase().includes(q)))}
function bindProducts(){$$("[data-product]").forEach(x=>x.onclick=()=>openProduct(x.dataset.product,x.dataset.placement||"unknown"))}
function renderCatalog(){const rows=filtered();$("#catalogGrid").innerHTML=rows.map(catalogCard).join("");$("#catalogEmpty").classList.toggle("show",rows.length===0);bindProducts()}
function render(){const n=state.products.length;document.body.classList.toggle("has-products",n>0);document.body.dataset.catalogCount=String(n);$("#selection").innerHTML=state.products.filter(x=>x.featured).slice(0,3).map(featured).join("");$("#showcase").innerHTML=state.products.slice(0,8).map(small).join("");bindProducts();renderCatalog()}
async function load(){try{const r=await fetch("/api/products?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw 0;const d=await r.json();state.products=Array.isArray(d.products)?d.products:[]}catch{state.products=[]}render()}
function applyLang(lang){state.lang=lang||"pt";document.documentElement.lang=state.lang==="pt"?"pt-BR":state.lang==="en"?"en-US":"es";$("#catalogTitle").textContent=text[state.lang].title;$("#catalogSearch").placeholder=text[state.lang].search;$("#catalogEmpty").textContent=text[state.lang].empty;render()}
function openCatalog(){const d=$("#catalogDialog");if(!d.open)d.showModal();setTimeout(()=>$("#catalogSearch").focus(),30)}
function geometry(){const img=$(".authority-picture img");if(!img)return;document.documentElement.dataset.renderWidth=String(Math.round(img.getBoundingClientRect().width));document.documentElement.dataset.viewportWidth=String(window.innerWidth);document.documentElement.dataset.horizontalOverflow=String(document.documentElement.scrollWidth>window.innerWidth)}
$$("[data-lang]").forEach(b=>b.onclick=()=>applyLang(b.dataset.lang));$$("[data-open-catalog]").forEach(b=>b.onclick=openCatalog);
$("#catalogSearch").oninput=e=>{state.query=e.target.value||"";renderCatalog()};$$("[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter||"";$$("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));renderCatalog()});$("[data-filter='']").classList.add("active");
window.addEventListener("resize",geometry);requestAnimationFrame(geometry);setTimeout(geometry,200);load();
})();