const state={products:[],filtered:[],visible:12,category:'Todos',lang:'pt',ecosystem:null};
const I18N={
 pt:{all:'Todos',buy:'Comprar',details:'Detalhes',projects:'Projetos e Loja',social:'Redes e Comunidade',company:'Empresa e Contato',empty:'Nenhum produto encontrado.',load:'Carregar mais',curated:'Achado selecionado pela curadoria BlackGold.',active:'ativo'},
 en:{all:'All',buy:'Buy',details:'Details',projects:'Projects and Store',social:'Social and Community',company:'Company and Contact',empty:'No products found.',load:'Load more',curated:'Selected by BlackGold premium curation.',active:'active'},
 es:{all:'Todos',buy:'Comprar',details:'Detalles',projects:'Proyectos y Tienda',social:'Redes y Comunidad',company:'Empresa y Contacto',empty:'No se encontraron productos.',load:'Cargar más',curated:'Selección de la curaduría premium BlackGold.',active:'activo'}
};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const t=k=>I18N[state.lang]?.[k]||I18N.pt[k]||k;
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function imageUrl(p){const v=p?.image||p?.image_original||'';if(!v)return '../assets/logo-cn-square.png';if(/^https?:\/\//i.test(v))return v;return '../'+v.replace(/^\.\//,'');}
function buyUrl(p){return p?.open_url||p?.short_url||p?.canonical_url||p?.check_url||'#';}
function productText(p){return p?.descricao_curta||p?.short_description||p?.description||p?.notes||t('curated');}
function priceText(p){return p?.price_text||p?.preco_atual||p?.price_current||p?.price||'';}
function tagsOf(p){return [...(p?.badges||[]),...(p?.categorias_secundarias||[]),p?.categoria_principal].filter(Boolean);}
function searchBlob(p){return [p.title,p.sku,p.id_busca,p.categoria_principal,...(p.categorias_secundarias||[]),...(p.badges||[]),...(p.aliases_busca||[]),productText(p)].filter(Boolean).join(' ').toLowerCase();}
function activeProducts(list){return (list||[]).filter(p=>p&&p.active!==false);}
function featuredProduct(){return state.products.find(p=>p.featured===true)||state.products.find(p=>p.quick_home===true)||state.products[0];}
function productCard(p){const price=priceText(p);const tags=tagsOf(p).slice(0,2);return `<article class="product-card" data-sku="${esc(p.sku||'')}"><div class="product-media"><img loading="lazy" src="${esc(imageUrl(p))}" alt="${esc(p.title||'Produto')}"></div><div class="product-card-body"><h3>${esc(p.title||'Produto')}</h3><div class="tags">${tags.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="product-meta"><span class="product-price">${price?esc(price):'BlackGold Find'}</span><span class="product-code">${esc(p.id_busca||'')}</span></div><div class="product-card-actions"><button class="btn ghost details-btn" data-sku="${esc(p.sku||'')}">${t('details')}</button><a class="btn primary" href="${esc(buyUrl(p))}" target="_blank" rel="noopener">${t('buy')}</a></div></div></article>`;}
function renderFeatured(){const p=featuredProduct();const root=$('#featuredProduct');if(!root)return;if(!p){root.innerHTML='<div class="loading">Sem seleção disponível.</div>';return;}const price=priceText(p);root.innerHTML=`<div class="featured-inner"><div class="featured-visual"><span class="featured-badge">BLACKGOLD PICK</span><img src="${esc(imageUrl(p))}" alt="${esc(p.title||'Produto')}"></div><div class="featured-content"><div class="eyebrow">CURADORIA EM DESTAQUE</div><h3>${esc(p.title||'Produto')}</h3><p>${esc(productText(p))}</p><div class="price-row">${price?`<span class="price">${esc(price)}</span>`:''}${p.desconto||p.discount?`<span class="discount">${esc(p.desconto||p.discount)}</span>`:''}</div><div class="tags">${tagsOf(p).slice(0,5).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="featured-actions"><a class="btn primary" href="${esc(buyUrl(p))}" target="_blank" rel="noopener">${t('buy')}</a><button class="btn ghost details-btn" data-sku="${esc(p.sku||'')}">${t('details')}</button></div></div></div>`;bindDetails();}
function topCategories(){const counts=new Map();state.products.forEach(p=>{const cat=p.categoria_principal||p.categorias_secundarias?.[0];if(cat)counts.set(cat,(counts.get(cat)||0)+1);});return [...counts].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([name])=>name);}
function renderCategories(){const root=$('#categoryChips');if(!root)return;const cats=[t('all'),...topCategories()];root.innerHTML=cats.map((c,i)=>`<button class="chip ${i===0?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$$('.chip').forEach(btn=>btn.addEventListener('click',()=>{$$('.chip').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.category=btn.dataset.cat;state.visible=12;applyFilters();}));}
function applyFilters(){const q=($('#searchInput')?.value||'').trim().toLowerCase();const allLabel=t('all');state.filtered=state.products.filter(p=>{const catOk=state.category==='Todos'||state.category==='All'||state.category===allLabel||tagsOf(p).includes(state.category);return catOk&&(!q||searchBlob(p).includes(q));});renderGrid();}
function renderGrid(){const root=$('#productGrid'),empty=$('#emptyState'),load=$('#loadMore');if(!root)return;root.innerHTML=state.filtered.slice(0,state.visible).map(productCard).join('');if(empty){empty.hidden=state.filtered.length>0;empty.textContent=t('empty');}if(load){load.hidden=state.filtered.length<=state.visible;load.textContent=t('load');}bindDetails();}
function bindDetails(){$$('.details-btn').forEach(btn=>btn.onclick=()=>openDialog(btn.dataset.sku));}
function openDialog(sku){const p=state.products.find(x=>x.sku===sku);if(!p)return;const dlg=$('#productDialog'),body=$('#dialogContent');if(!dlg||!body)return;body.innerHTML=`<div class="dialog-inner"><div class="dialog-media"><img src="${esc(imageUrl(p))}" alt="${esc(p.title||'Produto')}"></div><div class="dialog-copy"><div class="eyebrow">BLACKGOLD BEAUTY FINDS</div><h3>${esc(p.title||'Produto')}</h3><p>${esc(productText(p))}</p>${priceText(p)?`<div class="dialog-price">${esc(priceText(p))}</div>`:''}<div class="tags">${tagsOf(p).slice(0,8).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div>${p.id_busca?`<p><strong>Código:</strong> ${esc(p.id_busca)}</p>`:''}<div class="dialog-actions"><a class="btn primary" href="${esc(buyUrl(p))}" target="_blank" rel="noopener">${t('buy')}</a></div></div></div>`;dlg.showModal();}
function ecoIcon(item){const id=(item.id||item.kind||'').toLowerCase();if(id.includes('instagram'))return '◎';if(id.includes('tiktok'))return '♪';if(id.includes('youtube'))return '▶';if(id.includes('facebook'))return 'f';if(id.includes('telegram'))return '➤';if(id.includes('github'))return '◉';if(id.includes('linkedin'))return 'in';if(id.includes('contact'))return '✉';if(id.includes('preco'))return '▷';if(id.includes('fitnexus'))return 'A';if(id.includes('hub'))return '▣';if(id.includes('kwai'))return '⌘';return '◆';}
function localizedLabel(item){if(item.labels){const key=state.lang==='pt'?'pt-BR':state.lang==='en'?'en-US':'es-419';return item.labels[key]||Object.values(item.labels)[0];}return item.label||item.id||'BlackGold';}
function ecoCard(item){const label=localizedLabel(item);const kind=item.kind||'link';return `<a class="eco-card" href="${esc(item.url||'#')}" target="_blank" rel="noopener"><span class="eco-icon">${esc(ecoIcon(item))}</span><span class="eco-copy"><strong>${esc(label)}</strong><small>${t('active')} · ${esc(kind)}</small></span><span class="eco-arrow">›</span></a>`;}
function renderEcosystem(){const e=state.ecosystem,root=$('#ecosystemGroups');if(!e||!root)return;const projects=[...(e.hub?[e.hub]:[]),...(e.projects||[])];const channels=e.channels||[];const social=channels.filter(x=>['social','community'].includes(x.kind));const company=channels.filter(x=>['professional','company','contact'].includes(x.kind));const groups=[[t('projects'),'⬡',projects],[t('social'),'●',social],[t('company'),'▣',company]];root.innerHTML=groups.map(([title,icon,items])=>`<section class="eco-group"><div class="eco-group-title"><b>${icon}</b>${esc(title)}</div><div class="eco-grid">${items.map(ecoCard).join('')}</div></section>`).join('');}
function setLang(lang){state.lang=lang;$$('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));state.category='Todos';renderFeatured();renderCategories();applyFilters();renderEcosystem();}
async function boot(){try{const [productsRes,ecoRes]=await Promise.all([fetch('../produtos.json',{cache:'no-store'}),fetch('../ecosystem.json',{cache:'no-store'})]);if(!productsRes.ok)throw new Error('Falha ao carregar produtos');const productData=await productsRes.json();state.products=activeProducts(Array.isArray(productData)?productData:productData.products);state.filtered=[...state.products];if(ecoRes.ok)state.ecosystem=await ecoRes.json();const count=$('#productCount');if(count)count.textContent=state.products.length;renderFeatured();renderCategories();renderGrid();renderEcosystem();$('#searchInput')?.addEventListener('input',()=>{state.visible=12;applyFilters();});$('#loadMore')?.addEventListener('click',()=>{state.visible+=12;renderGrid();});$$('.lang').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));$('.dialog-close')?.addEventListener('click',()=>$('#productDialog')?.close());$('#productDialog')?.addEventListener('click',e=>{if(e.target.id==='productDialog')e.target.close();});}catch(err){console.error(err);const root=$('#productGrid');if(root)root.innerHTML='<div class="empty">Não foi possível carregar a vitrine agora.</div>';}}
boot();