services:
  - type: web
    name: la-famiglia-links
    env: docker
    dockerCommand: docker-compose -f docker-compose.render.yml up --build
    plan: free
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
