blank_issues_enabled: false
contact_links:
  - name: 🛠️ Suporte interno
    url: https://github.com/ProjetosCosaNostra/La_Famiglia_Links/issues
    about: Use os formulários abaixo para atualizar a vitrine.
