const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const state={products:[],eco:null,visible:8,locale:'pt-BR'};
const copy={
'pt-BR':{navToday:'Seleção do Dia',navStore:'Vitrine',navEco:'Ecossistema',heroA:'Achados com',heroB:'presença de luxo.',heroText:'Uma vitrine BlackGold mais clara, mais rápida e com foco direto no produto — sem perder a identidade que tornou a loja única.',seeProducts:'Ver produtos',openEco:'Abrir ecossistema',metricProducts:'produtos ativos',metricGlobal:'experiência global',metricIdentity:'identidade oficial',todayEyebrow:'SELEÇÃO DO DIA',todayTitle:'Uma escolha que merece destaque.',storeEyebrow:'VITRINE RÁPIDA',storeTitle:'Comprar ficou mais simples.',showMore:'Mostrar mais produtos',ecoA:'Ecossistema',ecoText:'Escolha diretamente o projeto, canal, comunidade ou contato desejado. Nenhum redirecionamento automático.',manifest:'Manifesto carregado. Escolha o destino.',projectsStore:'PROJETOS E LOJA',networks:'REDES E COMUNIDADE',business:'EMPRESA E CONTATO'},
'en-US':{navToday:'Today’s Pick',navStore:'Storefront',navEco:'Ecosystem',heroA:'Finds with',heroB:'luxury presence.',heroText:'A clearer, faster BlackGold storefront focused directly on the product — without losing the identity that makes the store unique.',seeProducts:'View products',openEco:'Open ecosystem',metricProducts:'active products',metricGlobal:'global experience',metricIdentity:'official identity',todayEyebrow:'TODAY’S PICK',todayTitle:'One choice worth highlighting.',storeEyebrow:'QUICK STOREFRONT',storeTitle:'Shopping made simpler.',showMore:'Show more products',ecoA:'BlackGold',ecoText:'Choose the project, channel, community or contact you want. No automatic redirection.',manifest:'Manifest loaded. Choose a destination.',projectsStore:'PROJECTS & STORE',networks:'NETWORKS & COMMUNITY',business:'COMPANY & CONTACT'},
'es-419':{navToday:'Selección del Día',navStore:'Vitrina',navEco:'Ecosistema',heroA:'Hallazgos con',heroB:'presencia de lujo.',heroText:'Una vitrina BlackGold más clara, rápida y enfocada directamente en el producto — sin perder la identidad que hace única a la tienda.',seeProducts:'Ver productos',openEco:'Abrir ecosistema',metricProducts:'productos activos',metricGlobal:'experiencia global',metricIdentity:'identidad oficial',todayEyebrow:'SELECCIÓN DEL DÍA',todayTitle:'Una elección que merece destaque.',storeEyebrow:'VITRINA RÁPIDA',storeTitle:'Comprar quedó más simple.',showMore:'Mostrar más productos',ecoA:'Ecosistema',ecoText:'Elige directamente el proyecto, canal, comunidad o contacto deseado. Sin redirección automática.',manifest:'Manifiesto cargado. Elige un destino.',projectsStore:'PROYECTOS Y TIENDA',networks:'REDES Y COMUNIDAD',business:'EMPRESA Y CONTACTO'}};
const iconMap={hub:'⌂',android_app:'▷',saas:'A',social:'●',community:'➤',professional:'◆',contact:'✉'};
function asset(src){if(!src)return '../assets/logo.png';if(/^https?:/i.test(src))return src;return src.startsWith('../')?src:`../${src.replace(/^\.\//,'')}`}
function target(p){return p.open_url||p.short_url||p.relink_open_url||p.canonical_url||p.resolved_url||'#'}
function safe(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function productPrice(p){return p.price_text||p.preco_atual||p.price||'Ver oferta'}
function tags(p,n=3){const values=[...(p.categorias_secundarias||[]),...(p.badges||[])];return [...new Set(values)].slice(0,n)}
function productCard(p){return `<article class="product-card" data-search="${safe([p.title,p.id_busca,...(p.badges||[]),...(p.categorias_secundarias||[])].join(' ').toLowerCase())}"><div class="product-image"><img loading="lazy" src="${safe(asset(p.image||p.image_original))}" alt="${safe(p.title)}"></div><div class="product-body"><div class="meta">${tags(p,2).map(x=>`<span class="tag">${safe(x)}</span>`).join('')}</div><h3>${safe(p.title)}</h3><div class="card-price">${safe(productPrice(p))}</div><div class="code">Código · ${safe(p.id_busca||'—')}</div><div class="product-actions"><button data-detail="${safe(p.sku)}">Ver detalhes</button><a class="buy" href="${safe(target(p))}" target="_blank" rel="noopener">Comprar</a></div></div></article>`}
function renderFeatured(){const p=state.products.find(x=>x.featured)||state.products.find(x=>x.quick_home&&x.price_text)||state.products.find(x=>x.quick_home)||state.products[0];const el=$('#featuredProduct');if(!p){el.textContent='Nenhum produto ativo.';return}el.classList.remove('skeleton');el.innerHTML=`<div class="feature-media"><img src="${safe(asset(p.image||p.image_original))}" alt="${safe(p.title)}"></div><div class="feature-info"><span class="eyebrow">BLACKGOLD SELECTED</span><div class="tags">${tags(p,4).map(x=>`<span class="tag">${safe(x)}</span>`).join('')}</div><h3>${safe(p.title)}</h3><div class="price">${safe(productPrice(p))}</div><p>${safe(p.descricao_curta||p.short_description||p.notes||'Produto selecionado pela curadoria BlackGold para facilitar sua compra.')}</p><div class="feature-actions"><a class="btn primary" href="${safe(target(p))}" target="_blank" rel="noopener">Comprar no Mercado Livre</a><button class="btn ghost" data-detail="${safe(p.sku)}">Ver detalhes</button></div></div>`}
function renderGrid(){const q=($('#searchInput')?.value||'').trim().toLowerCase();const list=q?state.products.filter(p=>[p.title,p.id_busca,...(p.badges||[]),...(p.categorias_secundarias||[]),...(p.aliases_busca||[])].join(' ').toLowerCase().includes(q)):state.products.slice(0,state.visible);$('#productGrid').innerHTML=list.map(productCard).join('')||'<p>Nenhum produto encontrado.</p>';$('#showMore').style.display=q||state.visible>=state.products.length?'none':'inline-block'}
function openProduct(sku){const p=state.products.find(x=>x.sku===sku);if(!p)return;$('#modalContent').innerHTML=`<div class="modal-body"><img src="${safe(asset(p.image||p.image_original))}" alt="${safe(p.title)}"><div><span class="eyebrow">COSA NOSTRA BLACKGOLD</span><h2>${safe(p.title)}</h2><div class="price">${safe(productPrice(p))}</div><p>${safe(p.descricao_curta||p.short_description||p.notes||'Confira preço, frete e disponibilidade no Mercado Livre antes de concluir.')}</p><div class="tags">${tags(p,6).map(x=>`<span class="tag">${safe(x)}</span>`).join('')}</div><p class="code">Código de busca: <strong>${safe(p.id_busca||'—')}</strong></p><div class="feature-actions"><a class="btn primary" href="${safe(target(p))}" target="_blank" rel="noopener">Comprar no Mercado Livre</a><button class="btn ghost" data-copy="${safe(p.id_busca||'')}">Copiar ID</button></div></div></div>`;$('#productModal').showModal()}
function ecoCard(item){const label=item.labels?.[state.locale]||item.label||item.id;return `<a class="eco-card" href="${safe(item.url)}" ${item.url?.startsWith('mailto:')?'':'target="_blank" rel="noopener"'}><span class="eco-icon">${iconMap[item.kind]||'◇'}</span><span><strong>${safe(label)}</strong><small>${safe((item.status||'active')+' · '+(item.kind||'link'))}</small></span><span class="eco-arrow">›</span></a>`}
function renderEco(){if(!state.eco)return;const projects=[state.eco.hub,...(state.eco.projects||[])];const channels=state.eco.channels||[];const social=channels.filter(x=>['social','community'].includes(x.kind));const business=channels.filter(x=>!['social','community'].includes(x.kind));$('#ecoProjects').innerHTML=projects.map(ecoCard).join('');$('#ecoSocial').innerHTML=social.map(ecoCard).join('');$('#ecoBusiness').innerHTML=business.map(ecoCard).join('')}
function applyLocale(locale){state.locale=locale;document.documentElement.lang=locale;$$('[data-locale]').forEach(b=>b.classList.toggle('active',b.dataset.locale===locale));$$('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(copy[locale]?.[key])el.textContent=copy[locale][key]});$('#searchInput').placeholder=locale==='en-US'?'Search product, category or code':locale==='es-419'?'Buscar producto, categoría o código':'Buscar produto, categoria ou código';renderEco()}
async function init(){try{const [productsRes,ecoRes]=await Promise.all([fetch('../produtos.json',{cache:'no-store'}),fetch('../ecosystem.json',{cache:'no-store'})]);const pdata=await productsRes.json();state.eco=await ecoRes.json();state.products=(pdata.products||[]).filter(p=>p.active!==false&&p.review_status!=='removido');$('#productCount').textContent=state.products.length;renderFeatured();renderGrid();renderEco()}catch(err){console.error(err);$('#featuredProduct').classList.remove('skeleton');$('#featuredProduct').innerHTML='<div class="feature-info"><h3>Não foi possível carregar o catálogo.</h3><p>Atualize a página em alguns instantes.</p></div>'}}
document.addEventListener('click',e=>{const detail=e.target.closest('[data-detail]');if(detail)openProduct(detail.dataset.detail);const cp=e.target.closest('[data-copy]');if(cp){navigator.clipboard?.writeText(cp.dataset.copy);cp.textContent='Copiado ✓'}const loc=e.target.closest('[data-locale]');if(loc)applyLocale(loc.dataset.locale)});$('#searchInput').addEventListener('input',renderGrid);$('#showMore').addEventListener('click',()=>{state.visible+=8;renderGrid()});$('.modal-close').addEventListener('click',()=>$('#productModal').close());$('#productModal').addEventListener('click',e=>{if(e.target===$('#productModal'))$('#productModal').close()});applyLocale('pt-BR');init();