(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const COMPARE_KEY="bg_compare";
function safeCompare(){try{const v=JSON.parse(localStorage.getItem(COMPARE_KEY)||"[]");return Array.isArray(v)?v.filter(x=>typeof x==="string").slice(0,3):[]}catch{localStorage.removeItem(COMPARE_KEY);return[]}}
function live(){let n=$("#uiStatus");if(!n){n=document.createElement("div");n.id="uiStatus";n.className="sr-only";n.setAttribute("role","status");n.setAttribute("aria-live","polite");n.setAttribute("aria-atomic","true");document.body.appendChild(n)}return n}
function announce(msg){const n=live();n.textContent="";setTimeout(()=>{n.textContent=msg},20)}
async function load(path,fallback){try{const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw 0;return await r.json()}catch{return fallback}}
function age(date){const d=new Date(String(date||"")+"T00:00:00Z");if(Number.isNaN(d.getTime()))return null;return Math.max(0,Math.floor((Date.now()-d.getTime())/86400000))}
function freshState(date){const a=age(date);return a===null?"unknown":a<=30?"recent":a<=90?"review":"stale"}
function closeMenu(returnFocus=false){document.body.classList.remove("menu-open");const b=$("#menuToggle");if(b){b.setAttribute("aria-expanded","false");b.textContent="Menu";if(returnFocus)b.focus()}}
function hardenMenu(){const b=$("#menuToggle"),n=$("#primaryNav");if(!b||!n)return;b.setAttribute("aria-label","Open primary navigation");b.addEventListener("click",()=>{setTimeout(()=>{const open=document.body.classList.contains("menu-open");b.setAttribute("aria-label",open?"Close primary navigation":"Open primary navigation");if(open){document.body.classList.add("nav-lock");n.querySelector("a")?.focus()}else document.body.classList.remove("nav-lock")},0)});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&document.body.classList.contains("menu-open")){document.body.classList.remove("nav-lock");closeMenu(true)}});window.addEventListener("resize",()=>{if(innerWidth>860&&document.body.classList.contains("menu-open")){document.body.classList.remove("nav-lock");closeMenu(false)}});n.addEventListener("click",e=>{if(e.target.closest("a")){document.body.classList.remove("nav-lock");closeMenu(false)}})}
function classifySources(ps){const bySlug=new Map(ps.map(p=>[p.slug,p]));$$('.product-card').forEach(card=>{const a=card.querySelector('a[href*="product.html?slug="]');if(!a)return;const slug=new URL(a.href,location.href).searchParams.get("slug"),p=bySlug.get(slug),pill=card.querySelector(".source-pill");if(!p||!pill)return;const st=freshState(p.source?.last_verified_at);pill.dataset.freshness=st;pill.title=`Source checked ${p.source?.last_verified_at||"date unavailable"}`;card.dataset.freshness=st});if(document.body.dataset.page==="product"){const slug=new URLSearchParams(location.search).get("slug"),p=bySlug.get(slug),lock=$(".commerce-lock");if(p&&lock&&!$(".source-health")){const st=freshState(p.source?.last_verified_at);lock.insertAdjacentHTML("beforebegin",`<div class="source-health" data-freshness="${st}"><span>Source health</span><b>${st==="recent"?"Recently checked":st==="review"?"Review soon":st==="stale"?"Source is stale":"Date unavailable"}</b><small>${esc(p.source?.publisher||"Source")} · ${esc(p.source?.last_verified_at||"unavailable")}</small></div>`)}}}
function catalogPolish(){if(document.body.dataset.page!=="products")return;const q=$("#search"),tools=$(".catalog-tools"),grid=$("#catalogGrid"),filters=$("#filters");if(!q||!tools||!grid||!filters)return;if(!$("#clearSearch")){const b=document.createElement("button");b.type="button";b.id="clearSearch";b.className="clear-search";b.textContent="Clear";b.hidden=!q.value;tools.insertBefore(b,filters);b.addEventListener("click",()=>{q.value="";q.dispatchEvent(new Event("input",{bubbles:true}));b.hidden=true;announce("Search cleared")});q.addEventListener("input",()=>{b.hidden=!q.value})}
 const normalizeEmpty=()=>{if(grid.querySelector(".product-card"))return;const text=grid.textContent.trim();if(!text||grid.querySelector(".v52-empty"))return;grid.innerHTML='<div class="v52-empty"><span>NO MATCH</span><h2>Nothing in this edit matches yet.</h2><p>Try another category or clear the search. We do not pad the index with unrelated products.</p><button class="btn ghost" type="button" id="resetCatalog">Reset Beauty Index</button></div>';$("#resetCatalog")?.addEventListener("click",()=>{q.value="";const all=filters.querySelector('[data-cat="All"]');all?.click();q.dispatchEvent(new Event("input",{bubbles:true}));announce("Beauty Index reset")})};
 new MutationObserver(()=>setTimeout(normalizeEmpty,0)).observe(grid,{childList:true,subtree:true});setTimeout(normalizeEmpty,100);
 filters.addEventListener("click",e=>{const b=e.target.closest("button[data-cat]");if(b)announce(`${b.dataset.cat} filter selected`)})}
function guideToolbar(gs){if(document.body.dataset.page!=="guides")return;const grid=$("#guideGrid");if(!grid||$("#guideToolbar"))return;const cats=["All",...new Set(gs.map(g=>g.category).filter(Boolean))];const wrap=document.createElement("section");wrap.id="guideToolbar";wrap.className="guide-toolbar";wrap.innerHTML=`<label class="guide-search"><span class="sr-only">Search buying guides</span><input id="guideSearch" type="search" placeholder="Search guides or decisions…"></label><div class="guide-filters">${cats.map(c=>`<button type="button" data-guide-cat="${esc(c)}" class="${c==="All"?"active":""}">${esc(c)}</button>`).join("")}</div><div id="guideMeta" class="guide-meta"></div>`;grid.before(wrap);$$('.guide-card').forEach((card,i)=>{card.dataset.guideCat=gs[i]?.category||"";card.dataset.guideText=card.textContent.toLowerCase()});let active="All";const input=$("#guideSearch"),meta=$("#guideMeta");const apply=()=>{const term=input.value.trim().toLowerCase();let shown=0;$$('.guide-card').forEach(card=>{const okCat=active==="All"||card.dataset.guideCat===active,okTerm=!term||card.dataset.guideText.includes(term),show=okCat&&okTerm;card.hidden=!show;if(show)shown++});meta.textContent=`${shown} buying guide${shown===1?"":"s"} in view`};wrap.addEventListener("click",e=>{const b=e.target.closest("[data-guide-cat]");if(!b)return;active=b.dataset.guideCat;$$('[data-guide-cat]').forEach(x=>x.classList.toggle("active",x===b));apply();announce(`${active} guides selected`)});input.addEventListener("input",apply);apply()}
function comparePolish(){if(document.body.dataset.page!=="compare")return;const v=$("#compareView");if(!v)return;const enhance=()=>{const grid=v.querySelector(".compare-grid");if(!grid||grid.dataset.v52)return;grid.dataset.v52="1";grid.setAttribute("role","list");grid.querySelectorAll(".compare-card").forEach(c=>c.setAttribute("role","listitem"));const tools=document.createElement("div");tools.className="compare-tools";tools.innerHTML='<span>Up to three products · no forced winner</span><button type="button" class="text-button" id="clearDesk">Clear desk</button>';grid.before(tools);$("#clearDesk")?.addEventListener("click",()=>{localStorage.removeItem(COMPARE_KEY);announce("Comparison desk cleared");location.reload()})};new MutationObserver(()=>setTimeout(enhance,0)).observe(v,{childList:true,subtree:true});setTimeout(enhance,100)}
function productTools(ps){if(document.body.dataset.page!=="product")return;const slug=new URLSearchParams(location.search).get("slug"),p=ps.find(x=>x.slug===slug);if(!p)return;document.title=`${p.name} | BlackGold Beauty Finds`;const actions=$(".product-copy .actions");if(actions&&!$("#copyResearchLink")){const b=document.createElement("button");b.type="button";b.id="copyResearchLink";b.className="btn ghost";b.textContent="Copy research link";actions.appendChild(b);b.addEventListener("click",async()=>{const url=location.href;try{await navigator.clipboard.writeText(url);b.textContent="Link copied";announce("Research link copied")}catch{const t=document.createElement("textarea");t.value=url;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove();b.textContent="Link copied";announce("Research link copied")}setTimeout(()=>b.textContent="Copy research link",1800)})}}
function detailTitle(gs){if(document.body.dataset.page!=="guide-detail")return;const key=new URLSearchParams(location.search).get("slug"),g=gs.find((x,i)=>(x.id||x.slug||String(i))===key)||gs[0];if(g)document.title=`${g.title} | BlackGold Buying Guide`}
function compareAnnouncements(){document.addEventListener("click",e=>{const b=e.target.closest("[data-v51-compare]");if(b){const id=b.dataset.v51Compare,had=safeCompare().includes(id);setTimeout(()=>announce(had?"Removed from comparison":"Added to comparison"),30)}const r=e.target.closest("[data-remove]");if(r)setTimeout(()=>announce("Removed from comparison"),30)},true)}
async function init(){live();hardenMenu();catalogPolish();comparePolish();compareAnnouncements();const [pd,gd]=await Promise.all([load("data/products.json",{products:[]}),load("data/guides.json",{guides:[]})]);const ps=Array.isArray(pd.products)?pd.products:[],gs=Array.isArray(gd.guides)?gd.guides:[];classifySources(ps);productTools(ps);detailTitle(gs);setTimeout(()=>guideToolbar(gs),160);const mo=new MutationObserver(()=>{classifySources(ps);if(document.body.dataset.page==="guides")guideToolbar(gs)});mo.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(init,80),{once:true});else setTimeout(init,80);
})();
