function authorized(request,env){const token=request.headers.get('x-admin-token')||'';return !!env.BG_ADMIN_TOKEN&&token===env.BG_ADMIN_TOKEN;}
const json=(data,status=200)=>Response.json(data,{status,headers:{'cache-control':'no-store'}});
function slugify(v,fallback=''){return String(v||fallback).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9-]+/g,'-').replace(/^-|-$/g,'')}
function affiliateUrl(value){try{const u=new URL(String(value||''));const h=u.hostname.toLowerCase();return u.protocol==='https:'&&(h==='meli.la'||h==='mercadolivre.com.br'||h.endsWith('.mercadolivre.com.br'))?u.href:null}catch{return null}}
const cleanMlb=v=>{const s=String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');return !s?null:/^MLB\d{6,}$/.test(s)?s:false};
const cleanVariation=v=>{const s=String(v||'').trim();return !s?null:/^\d+$/.test(s)?s:false};
function normalizeCatalog(body){const catalog=cleanMlb(body.marketplace_catalog_product_id);if(catalog===false)return {error:'invalid_marketplace_catalog_product_id'};const raw=String(body.marketplace_expected_attributes_json||'').trim();let attrs=null;if(raw){try{const p=JSON.parse(raw);if(!p||Array.isArray(p)||typeof p!=='object')return {error:'invalid_marketplace_expected_attributes'};attrs=JSON.stringify(p)}catch{return {error:'invalid_marketplace_expected_attributes_json'}}}return {catalog,attrs};}
function normalizeLinks(body,fallback){const rows=[],seen=new Set();for(const item of (body.links||[]).slice(0,5)){if(!item?.url)continue;const slot=Number(item.slot),url=affiliateUrl(item.url),itemId=cleanMlb(item.marketplace_item_id||item.item_id),variationId=cleanVariation(item.marketplace_variation_id||item.variation_id);if(!Number.isInteger(slot)||slot<1||slot>5||seen.has(slot))return {error:'invalid_or_duplicate_link_slot'};if(!url)return {error:'invalid_affiliate_url'};if(itemId===false)return {error:'invalid_marketplace_item_id'};if(variationId===false)return {error:'invalid_marketplace_variation_id'};seen.add(slot);rows.push({slot,url,fingerprint:String(item.fingerprint||fallback||'').trim(),itemId,variationId});}return {rows};}
async function current(env,id){const product=await env.DB.prepare(`SELECT * FROM products WHERE id=?`).bind(id).first();if(!product)return null;const links=await env.DB.prepare(`SELECT * FROM product_links WHERE product_id=? ORDER BY slot`).bind(id).all();return {...product,links:links.results||[]};}

export async function onRequestPut({request,env,params}){
  if(!authorized(request,env))return json({error:'unauthorized'},401);
  const id=String(params.id||''),before=await current(env,id);if(!before)return json({error:'not_found'},404);
  const body=await request.json().catch(()=>({}));if(!body.title_pt||!body.category)return json({error:'title_pt_and_category_required'},400);
  const slug=slugify(body.slug,before.slug),catalog=normalizeCatalog(body),links=normalizeLinks(body,slug);if(catalog.error)return json({error:catalog.error},400);if(links.error)return json({error:links.error},400);
  const catalogChanged=String(before.marketplace_catalog_product_id||'')!==String(catalog.catalog||'')||String(before.marketplace_expected_attributes_json||'')!==String(catalog.attrs||'');
  const now=new Date().toISOString(),incoming=new Map(links.rows.map(x=>[x.slot,x])),oldBySlot=new Map((before.links||[]).map(x=>[Number(x.slot),x])),statements=[];
  const productIdentity=catalogChanged?(catalog.catalog?'catalog_only':'pending'):(before.marketplace_identity_status||'pending');
  statements.push(env.DB.prepare(`UPDATE products SET slug=?,title_pt=?,title_en=?,title_es=?,brand=?,category=?,description_pt=?,status=?,market='BR',affiliate_ready=?,featured=?,image_path=?,image_status=?,updated_at=?,marketplace_site_id='MLB',marketplace_catalog_product_id=?,marketplace_expected_attributes_json=?,marketplace_identity_status=?,marketplace_title=?,marketplace_permalink=?,marketplace_status=?,marketplace_seller_id=?,marketplace_seller_level=?,marketplace_last_checked_at=?,marketplace_last_reason=? WHERE id=?`).bind(slug,body.title_pt,body.title_en||null,body.title_es||null,body.brand||null,body.category,body.description_pt||null,body.status||'draft',body.affiliate_ready?1:0,body.featured?1:0,body.image_path||null,body.image_status||before.image_status||'pending',now,catalog.catalog,catalog.attrs,productIdentity,catalogChanged?null:before.marketplace_title,catalogChanged?null:before.marketplace_permalink,catalogChanged?null:before.marketplace_status,catalogChanged?null:before.marketplace_seller_id,catalogChanged?null:before.marketplace_seller_level,catalogChanged?null:before.marketplace_last_checked_at,catalogChanged?(catalog.catalog?'catalog_changed_pending_verification':'catalog_identity_missing'):before.marketplace_last_reason,id));
  if(catalogChanged)statements.push(env.DB.prepare(`UPDATE product_links SET marketplace_catalog_product_id=NULL,marketplace_identity_status=CASE WHEN marketplace_item_id IS NULL OR marketplace_item_id='' THEN 'pending' ELSE 'declared' END,marketplace_seller_id=NULL,marketplace_seller_level=NULL,marketplace_last_checked_at=NULL,marketplace_last_reason='canonical_catalog_changed_pending_reverification',health_status='unknown',variant_match=0,fail_count=0,last_checked_at=NULL,last_ok_at=NULL,last_http_status=NULL,last_reason=NULL,last_final_url=NULL,last_title=NULL WHERE product_id=?`).bind(id));

  for(const row of links.rows){
    const old=oldBySlot.get(row.slot);const same=!catalogChanged&&old&&old.affiliate_url===row.url&&String(old.variant_fingerprint||'')===row.fingerprint&&String(old.marketplace_item_id||'')===String(row.itemId||'')&&String(old.marketplace_variation_id||'')===String(row.variationId||'');
    if(old&&same)statements.push(env.DB.prepare(`UPDATE product_links SET priority=?,is_active=1 WHERE product_id=? AND slot=?`).bind(row.slot,id,row.slot));
    else if(old)statements.push(env.DB.prepare(`UPDATE product_links SET affiliate_url=?,priority=?,variant_fingerprint=?,marketplace_item_id=?,marketplace_variation_id=?,marketplace_catalog_product_id=NULL,marketplace_identity_status=?,marketplace_seller_id=NULL,marketplace_seller_level=NULL,marketplace_last_checked_at=NULL,marketplace_last_reason=?,health_status='unknown',variant_match=0,fail_count=0,last_checked_at=NULL,last_ok_at=NULL,last_http_status=NULL,last_reason=NULL,last_final_url=NULL,last_title=NULL,is_active=1 WHERE product_id=? AND slot=?`).bind(row.url,row.slot,row.fingerprint,row.itemId,row.variationId,row.itemId?'declared':'pending',catalogChanged?'canonical_catalog_changed_pending_reverification':'listing_identity_changed_pending_verification',id,row.slot));
    else statements.push(env.DB.prepare(`INSERT INTO product_links(product_id,slot,affiliate_url,priority,health_status,fail_count,variant_fingerprint,is_active,variant_match,marketplace_item_id,marketplace_variation_id,marketplace_identity_status,marketplace_last_reason) VALUES(?,?,?,?,'unknown',0,?,1,0,?,?,?,?)`).bind(id,row.slot,row.url,row.slot,row.fingerprint,row.itemId,row.variationId,row.itemId?'declared':'pending',row.itemId?'listing_declared_pending_verification':'listing_identity_missing'));
  }
  for(const old of before.links||[])if(!incoming.has(Number(old.slot))&&Number(old.is_active)!==0)statements.push(env.DB.prepare(`UPDATE product_links SET is_active=0 WHERE product_id=? AND slot=?`).bind(id,old.slot));
  const audit={...body,slug,marketplace_catalog_product_id:catalog.catalog,marketplace_expected_attributes_json:catalog.attrs,links:links.rows};
  statements.push(env.DB.prepare(`INSERT INTO admin_audit(action,entity_type,entity_id,actor,before_json,after_json) VALUES('update','product',?,'admin',?,?)`).bind(id,JSON.stringify(before),JSON.stringify(audit)));
  await env.DB.batch(statements);return json({ok:true,product:await current(env,id)});
}

export async function onRequestDelete({request,env,params}){
  if(!authorized(request,env))return json({error:'unauthorized'},401);
  const id=String(params.id||''),before=await current(env,id);if(!before)return json({error:'not_found'},404);const now=new Date().toISOString();
  await env.DB.batch([env.DB.prepare(`UPDATE products SET status='archived',affiliate_ready=0,updated_at=? WHERE id=?`).bind(now,id),env.DB.prepare(`UPDATE product_links SET is_active=0 WHERE product_id=?`).bind(id),env.DB.prepare(`INSERT INTO admin_audit(action,entity_type,entity_id,actor,before_json) VALUES('archive','product',?,'admin',?)`).bind(id,JSON.stringify(before))]);
  return json({ok:true,id,status:'archived'});
}