INSERT OR IGNORE INTO marketplace_reconciliation
(id,product_id,source,source_ref,candidate_catalog_product_id,candidate_title,classification,confidence,reason,evidence_json)
VALUES
('recon-bg-us-0001-legacy','bg-us-0001','legacy_v38','meli.la/2Cz4YTk',NULL,NULL,'unresolved',0.0,'no_catalog_candidate_tied_to_legacy_offer','{"legacy_sku":"refil-creme-acetinado-hidratante-corporal-lily-250g","legacy_title":"Refil Creme Acetinado Hidratante Corporal Para Pele Lily 250g","guardian_bucket":"forte_evidencia","note":"legacy record confirms affiliate route, not catalog identity"}'),
('recon-bg-us-0002-legacy','bg-us-0002','legacy_v38','meli.la/1GawSXm',NULL,NULL,'unresolved',0.0,'no_catalog_candidate_tied_to_legacy_offer','{"legacy_sku":"sabonete-facial-garnier-uniform-matte-vitamina-c-120g","legacy_title":"Garnier SkinActive Uniform & Matte Vitamina C 120g","note":"legacy record has no card catalog id"}'),
('recon-bg-us-0003-legacy','bg-us-0003','legacy_v38','meli.la/1kPMdsr',NULL,NULL,'conflict',0.0,'quantity_conflict_6ml_vs_16g','{"legacy_sku":"lip-oil-volumizador-labial-epidrat-hyalu-berry-fps30-6ml","legacy_title":"Lip Oil Volumizador Labial Epidrat Hyalu Berry FPS 30 6ml","aliases_include":["epidrat hyalu 6ml","epidrat hyalu 16g"],"note":"do not promote until exact pack/quantity is proven"}'),
('recon-bg-us-0004-legacy','bg-us-0004','legacy_v38','meli.la/22qx74W',NULL,NULL,'unresolved',0.0,'no_catalog_candidate_tied_to_legacy_offer','{"legacy_sku":"kit-pinceis-maquiagem-13-pecas-estojo-rose","legacy_title":"Kit de Pincéis de Maquiagem 13 Peças com Estojo Rosé","note":"affiliate route exists but no catalog id evidence found"}'),
('recon-bg-us-0005-catalog','bg-us-0005','legacy_card_catalog','catalog-title-search','MLB70194949','Escova Secadora De Cabelos Britânia Bec07r Soft 4 Em 1 1300w Cor Rosa-claro','probable',0.8163,'catalog_candidate_requires_voltage_color_verification','{"legacy_sku":"escova-secadora-britania-bec07r-4em1-1300w-rosa","affiliate_url":"https://meli.la/1Vd3P8y","match_method":"catalog-title-search","source_match_score":0.8163,"required_checks":["BEC07R","1300W","voltage","color"]}'),
('recon-bg-us-0006-catalog','bg-us-0006','legacy_card_catalog','catalog-title-search','MLB76734925','Corretivo Líquido Alta Cobertura Ruby Rose Stay Fix - Cores Tom C 02','conflict',0.9628,'catalog_candidate_has_specific_shade_c02','{"legacy_sku":"corretivo-liquido-alta-cobertura-ruby-rose-stay-fix-cores-zrxy","affiliate_url":"https://meli.la/1XoHJ5m","match_method":"catalog-title-search","source_match_score":0.9628,"conflict":"current BlackGold product does not declare shade C 02"}'),
('recon-bg-us-0007-catalog','bg-us-0007','legacy_card_catalog','affiliate-page-catalog','MLB72180954','Paleta De Maquiagem 28 Sombras Nude + Pinceis - Belle Angel Paleta De Sombra','probable',0.95,'strong_catalog_evidence_old_affiliate_differs_from_current','{"legacy_sku":"paleta-maquiagem-belle-angel-28-sombras-nude-pinceis-sombra-28-cores","legacy_affiliate_url":"https://meli.la/2ZTeVJ2","current_affiliate_url":"https://meli.la/2VCv36B","match_method":"affiliate-page-catalog","source_match_score":1.0,"required_check":"prove current affiliate offer maps to same exact catalog product"}'),
('recon-bg-us-0008-catalog','bg-us-0008','legacy_card_catalog','catalog-title-search','MLB16048715','Floratta Blue Desodorante Colônia Feminino O Boticário 75ml','conflict',0.8539,'catalog_candidate_blue_not_my_blue','{"legacy_sku":"o-boticario-floratta-my-blue-colonia-75ml","affiliate_url":"https://meli.la/1D1EKm5","match_method":"catalog-title-search","source_match_score":0.8539,"conflict":"candidate title is Floratta Blue; current product is Floratta My Blue"}');