(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function load(path,fallback){try{const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw 0;return await r.json()}catch{return fallback}}
function age(date){const d=new Date(String(date||"")+"T00:00:00Z");if(Number.isNaN(d.getTime()))return null;return Math.max(0,Math.floor((Date.now()-d)/86400000))}
function fresh(date){const a=age(date);return a===null?{label:"date unavailable",cls:"stale"}:a<=30?{label:`${a}d · recent`,cls:"recent"}:a<=90?{label:`${a}d · review soon`,cls:"review"}:{label:`${a}d · stale`,cls:"stale"}}
function nav(){const p=document.body.dataset.page;if(["methodology","ledger","disclosure","privacy","terms","corrections","ecosystem"].includes(p))$$(".site-header nav a").forEach(a=>{if(a.getAttribute("href")==="methodology.html")a.setAttribute("aria-current","page")})}
async function methodology(){if(document.body.dataset.page!=="methodology")return;const [pd,gd,cd,rd]=await Promise.all([load("data/products.json",{products:[]}),load("data/guides.json",{guides:[]}),load("data/campaigns.json",{campaigns:[]}),load("data/retailer-links.json",{links:[]})]);const ps=Array.isArray(pd.products)?pd.products:[],gs=Array.isArray(gd.guides)?gd.guides:[],cs=Array.isArray(cd.campaigns)?cd.campaigns:[],ls=Array.isArray(rd.links)?rd.links:[];const v=ls.filter(x=>x.public_state==="verified").length,locked=Math.max(ps.length-v,ls.filter(x=>x.public_state!=="verified").length),vals={statusProducts:ps.length,statusFresh:ps.filter(p=>(age(p.source?.last_verified_at)??999)<=30).length,statusVerified:v,statusLocked:locked,statusGuides:gs.length,statusCampaigns:cs.length};Object.entries(vals).forEach(([id,n])=>{const e=document.getElementById(id);if(e)e.textContent=String(n)});const note=$("#trustStatusNote");if(note)note.textContent="Live values read from the current staging registries."}
async function ledger(){if(document.body.dataset.page!=="ledger")return;const d=await load("data/products.json",{products:[]}),ps=Array.isArray(d.products)?d.products:[],grid=$("#ledgerGrid"),q=$("#ledgerSearch"),meta=$("#ledgerSummary");function render(){const t=(q?.value||"").trim().toLowerCase(),rows=ps.filter(p=>!t||[p.brand,p.name,p.category,p.retailer_observed,p.source?.publisher,p.source?.type].join(" ").toLowerCase().includes(t));if(meta)meta.textContent=`${rows.length} of ${ps.length} research records`;if(grid)grid.innerHTML=rows.map(p=>{const f=fresh(p.source?.last_verified_at);return `<article class="ledger-row"><div><b>${esc(p.name)}</b><small>${esc(p.brand)} · ${esc(p.category)}</small></div><div><b>${esc(p.source?.publisher||"Unavailable")}</b><small>${esc(p.source?.type||"source")}</small></div><div><b>${esc(p.retailer_observed||p.retailer||"Unavailable")}</b><small>retailer observed</small></div><div><b>${esc(p.source?.last_verified_at||"—")}</b><small>verified</small></div><div><span class="ledger-status ${f.cls}">${esc(f.label)}</span><small><a href="product.html?slug=${encodeURIComponent(p.slug)}">Open research →</a></small></div></article>`}).join("")||'<p>No research record matches this search.</p>'}q?.addEventListener("input",render);render()}
nav();methodology();ledger();
})();