(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const storeKey="bg_compare";
function safeCompare(){try{const v=JSON.parse(localStorage.getItem(storeKey)||"[]");return Array.isArray(v)?v.filter(x=>typeof x==="string").slice(0,3):[]}catch{localStorage.removeItem(storeKey);return[]}}
function saveCompare(v){localStorage.setItem(storeKey,JSON.stringify([...new Set(v)].slice(0,3)));updateCount()}
function updateCount(){const e=$("#compareCount");if(e)e.textContent=safeCompare().length}
async function load(path,fallback){try{const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw 0;return await r.json()}catch{return fallback}}
function age(date){const d=new Date(String(date||"")+"T00:00:00Z");if(Number.isNaN(d.getTime()))return null;return Math.max(0,Math.floor((Date.now()-d)/86400000))}
function freshness(date){const a=age(date);return a===null?"date unavailable":a<=30?`${a}d · recent`:a<=90?`${a}d · review soon`:`${a}d · stale`}
function productCard(p){return `<article class="product-card"><a class="product-media" href="product.html?slug=${encodeURIComponent(p.slug)}"><span class="label">${esc(p.category)}</span><img loading="lazy" decoding="async" src="${esc(p.image)}" alt="${esc(p.name)} research illustration"></a><p class="brandline">${esc(p.brand)}</p><h3><a href="product.html?slug=${encodeURIComponent(p.slug)}">${esc(p.name)}</a></h3><p>${esc(p.summary)}</p><div class="card-bottom"><span class="source-pill">${esc(p.source?.publisher||"Source")} · ${esc(freshness(p.source?.last_verified_at))}</span><a href="product.html?slug=${encodeURIComponent(p.slug)}">Research →</a></div></article>`}
async function products(){const d=await load("data/products.json",{products:[]});return Array.isArray(d.products)?d.products:[]}
async function retailer(){return await load("data/retailer-links.json",{links:[]})}
async function home(){const ps=await products(),rg=await retailer();$("#metricProducts").textContent=ps.length;$("#metricFresh").textContent=ps.filter(p=>(age(p.source?.last_verified_at)??999)<=30).length;const links=Array.isArray(rg.links)?rg.links:[];$("#metricRoutes").textContent=links.filter(x=>x.public_state==="verified").length;$("#featuredGrid").innerHTML=ps.slice(0,4).map(productCard).join("")}
async function catalog(){const ps=await products(),cats=["All",...new Set(ps.map(p=>p.category))],f=$("#filters"),q=$("#search"),grid=$("#catalogGrid"),meta=$("#catalogMeta");let active=new URLSearchParams(location.search).get("category")||"All";if(!cats.includes(active))active="All";f.innerHTML=cats.map(c=>`<button data-cat="${esc(c)}" class="${c===active?"active":""}">${esc(c)}</button>`).join("");const render=()=>{const term=q.value.trim().toLowerCase();const rows=ps.filter(p=>(active==="All"||p.category===active)&&(!term||[p.brand,p.name,p.summary,p.best_for,...(p.tags||[])].join(" ").toLowerCase().includes(term)));grid.innerHTML=rows.map(productCard).join("")||"<p>No products match this filter.</p>";meta.textContent=`${rows.length} researched product${rows.length===1?"":"s"} · commercial links remain separately gated`};f.addEventListener("click",e=>{const b=e.target.closest("button[data-cat]");if(!b)return;active=b.dataset.cat;$$('.filters button').forEach(x=>x.classList.toggle('active',x===b));const u=new URL(location.href);active==="All"?u.searchParams.delete("category"):u.searchParams.set("category",active);history.replaceState(null,"",u);render()});q.addEventListener("input",render);render()}
async function product(){const ps=await products(),slug=new URLSearchParams(location.search).get("slug"),p=ps.find(x=>x.slug===slug),view=$("#productView");if(!p){view.innerHTML="<h1>Research record not found.</h1>";return}document.title=`${p.name} | BlackGold`;const selected=safeCompare().includes(p.id);view.innerHTML=`<article class="product-detail"><div class="product-hero-media"><img decoding="async" fetchpriority="high" src="${esc(p.image)}" alt="${esc(p.name)} research illustration"></div><div class="product-copy"><p class="brandname">${esc(p.brand)} · ${esc(p.category)}</p><h1>${esc(p.name)}</h1><p class="lede">${esc(p.summary)}</p><div class="actions"><button class="btn ${selected?"ghost":"primary"}" id="compareToggle">${selected?"Remove from comparison":"Add to comparison"}</button><a class="btn ghost" href="compare.html">Open Comparison Desk</a></div><div class="fact-grid"><div class="fact"><span>Best for</span><b>${esc(p.best_for)}</b></div><div class="fact"><span>Source status</span><b>${esc(p.truth_status)}</b></div><div class="fact"><span>Retailer observed</span><b>${esc(p.retailer_observed||p.retailer)}</b></div><div class="fact"><span>Last source check</span><b>${esc(p.source?.last_verified_at||"Unavailable")}</b></div></div><section class="research-block"><h2>Why it made the edit</h2><p>${esc(p.why_selected)}</p></section><section class="research-block"><h2>Limitations to keep in view</h2><p>${esc(p.limitations)}</p></section><section class="research-block"><h2>Source</h2><p>${esc(p.source?.publisher||"Unavailable")} · ${esc(p.source?.type||"source")} · ${esc(freshness(p.source?.last_verified_at))}</p></section><aside class="commerce-lock"><b>Commercial route locked</b><p>This research record does not become a shopping link until the separate retailer verification gate passes.</p></aside></div></article>`;$("#compareToggle").addEventListener("click",()=>{let a=safeCompare();if(a.includes(p.id))a=a.filter(x=>x!==p.id);else if(a.length<3)a.push(p.id);else{$("#compareToggle").textContent="Comparison holds up to three products";return}saveCompare(a);location.reload()})}
async function compare(){const ps=await products(),ids=safeCompare(),rows=ids.map(id=>ps.find(p=>p.id===id)).filter(Boolean),v=$("#compareView");saveCompare(rows.map(p=>p.id));if(!rows.length){v.innerHTML='<div class="guide-card"><h2>Your desk is empty.</h2><p>Add products from the Beauty Index or a research page.</p><a class="btn primary" href="products.html">Browse the Beauty Index</a></div>';return}v.innerHTML=`<div class="compare-grid">${rows.map(p=>`<article class="compare-card"><p class="brandline">${esc(p.brand)}</p><h2>${esc(p.name)}</h2><div class="compare-row"><span>Best for</span>${esc(p.best_for)}</div><div class="compare-row"><span>Why selected</span>${esc(p.why_selected)}</div><div class="compare-row"><span>Limitations</span>${esc(p.limitations)}</div><div class="compare-row"><span>Research status</span>${esc(p.truth_status)}</div><button class="btn ghost small" data-remove="${esc(p.id)}">Remove</button></article>`).join("")}</div>`;v.addEventListener("click",e=>{const b=e.target.closest("[data-remove]");if(!b)return;saveCompare(safeCompare().filter(x=>x!==b.dataset.remove));compare()})}
function guideTitle(g){return g.title||g.question||g.name||g.slug||"Buying guide"}function guideSummary(g){return g.summary||g.intro||g.description||g.promise||"A decision guide grounded in the current research edit."}
async function guides(){const d=await load("data/guides.json",{guides:[]}),gs=Array.isArray(d.guides)?d.guides:[],v=$("#guideGrid");v.innerHTML=gs.map((g,i)=>`<article class="guide-card"><p class="kicker">GUIDE ${String(i+1).padStart(2,"0")}</p><h2>${esc(guideTitle(g))}</h2><p>${esc(guideSummary(g))}</p><a href="guide-detail.html?slug=${encodeURIComponent(g.slug||g.id||i)}">Open guide →</a></article>`).join("")||"<p>No guides available.</p>"}
async function guideDetail(){const d=await load("data/guides.json",{guides:[]}),gs=Array.isArray(d.guides)?d.guides:[],key=new URLSearchParams(location.search).get("slug"),g=gs.find((x,i)=>(x.slug||x.id||String(i))===key)||gs[0],v=$("#guideView");if(!g){v.innerHTML="<h1>Guide not found.</h1>";return}const steps=g.steps||g.checks||g.buying_checks||g.sections||[];v.innerHTML=`<article class="guide-detail"><p class="kicker">${esc(g.category||"BUYING GUIDE")}</p><h1>${esc(guideTitle(g))}</h1><p class="lede">${esc(guideSummary(g))}</p>${Array.isArray(steps)?steps.map((s,i)=>`<section class="guide-step"><p class="kicker">STEP ${i+1}</p><h2>${esc(typeof s==="string"?s:(s.title||s.label||`Decision ${i+1}`))}</h2>${typeof s==="object"&&s.text?`<p>${esc(s.text)}</p>`:""}</section>`).join(""):""}<p><a class="btn ghost" href="guide.html">Back to guides</a></p></article>`}
updateCount();const page=document.body.dataset.page;({home,products:catalog,product,compare,guides,"guide-detail":guideDetail}[page]||(()=>{}))();
})();
