const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={products:[],filter:'Todos',lang:'pt'};
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const img=p=>p?.image?.startsWith('http')?p.image:`./${String(p?.image||'assets/logo-cn-square.png').replace(/^\.\//,'')}`;
const price=p=>p?.price||'BlackGold Find';
const text=p=>p?.description||'Achado selecionado pela curadoria BlackGold.';
function score(p){let s=0;const blob=[p.title,p.category,...(p.secondary||[]),...(p.badges||[])].join(' ').toLowerCase();if(p.featured)s+=20;if(p.price)s+=8;if(/moda|vestido|conjunto|bolsa|sapato|perfume|maquiagem|beleza/.test(blob))s+=5;if(/precisa_relink|relink/.test(text(p).toLowerCase()))s-=8;return s}
function picks(n=3){return [...state.products].sort((a,b)=>score(b)-score(a)).slice(0,n)}
function cardFeatured(p){return `<article class="featured-card"><div class="featured-img"><img src="${esc(img(p))}" alt="${esc(p.title)}"></div><div class="featured-info"><h3>${esc(p.title)}</h3><small>${esc(p.category||'BlackGold Find')}</small><p>${esc(text(p))}</p><div class="price">${esc(price(p))}</div><button data-sku="${esc(p.sku)}">Ver detalhes <span>→</span></button></div></article>`}
function cardProduct(p){return `<article class="product-card"><button data-sku="${esc(p.sku)}"><div class="product-media"><img src="${esc(img(p))}" loading="lazy" alt="${esc(p.title)}"></div><h3>${esc(p.title)}</h3><div class="price">${esc(price(p))}</div></button></article>`}
function render(){const featured=picks(3);$('#featured').innerHTML=featured.map(cardFeatured).join('');let list=state.products.filter(p=>{if(state.filter==='Todos')return true;const blob=[p.category,...(p.secondary||[]),...(p.badges||[])].join(' ').toLowerCase();const q=state.filter.toLowerCase();return q==='beleza'?/beleza|maquiagem|perfume|skincare|cuidado/.test(blob):q==='moda'?/moda|vestido|conjunto|roupa|calça|blusa|saia/.test(blob):q==='acessórios'?/acess|bolsa|sapato|sandália|relógio|óculos|brinco|colar|cinto/.test(blob):/autocuidado|cuidado pessoal|skincare|beleza/.test(blob)});list=[...list].sort((a,b)=>score(b)-score(a)).slice(0,8);$('#productRow').innerHTML=list.map(cardProduct).join('');bindDetails()}
function bindDetails(){$$('[data-sku]').forEach(b=>b.onclick=()=>openProduct(b.dataset.sku))}
function openProduct(sku){const p=state.products.find(x=>x.sku===sku);if(!p)return;$('#modalBody').innerHTML=`<div class="modal-grid"><img src="${esc(img(p))}" alt="${esc(p.title)}"><div class="modal-copy"><small>BLACKGOLD BEAUTY FINDS</small><h3>${esc(p.title)}</h3><p>${esc(text(p))}</p><div class="price">${esc(price(p))}</div>${p.id_busca?`<p><b>Código Mercado Livre:</b> ${esc(p.id_busca)}</p>`:''}<a class="btn gold" href="${esc(p.url||'#')}" target="_blank" rel="noopener">Comprar no Mercado Livre →</a></div></div>`;$('#modal').showModal()}
function setHero(){const fashion=state.products.find(p=>/conjunto|vestido|alfaiataria|blusa|calça/i.test([p.title,p.category,...(p.secondary||[])].join(' ')))||picks(1)[0];if(fashion){$('#heroModel').style.backgroundImage=`url("${img(fashion).replace(/"/g,'')}")`}}
async function loadEco(){try{const r=await fetch('./ecosystem.json',{cache:'no-store'});if(!r.ok)return;const e=await r.json();const all=[...(e.hub?[e.hub]:[]),...(e.projects||[]),...(e.channels||[])];const find=rx=>all.find(x=>rx.test(`${x.id||''} ${x.label||''} ${JSON.stringify(x.labels||{})}`));for(const [key,rx] of Object.entries({hub:/hub|loja/i,instagram:/instagram/i,youtube:/youtube/i,telegram:/telegram/i,github:/github/i})){const item=find(rx),a=$(`[data-eco="${key}"]`);if(item?.url&&a)a.href=item.url}}catch{}}
async function boot(){const r=await fetch('./catalog.json',{cache:'no-store'});const d=await r.json();state.products=d.products||[];$('#count').textContent=state.products.length||193;setHero();render();loadEco();$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;render()});$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));$('.close').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')e.target.close()})}
boot().catch(console.error);
